### ISSUE TITLE
AttributeError: 'Distribution' object has no attribute 'install_requires'

### ISSUE THREAD

**Issue by lwm** [parsonsmatt/intero-neovim#89]
https://travis-ci.org/parsonsmatt/intero-neovim/jobs/271437847

```
  Found existing installation: setuptools 36.2.0

    Uninstalling setuptools-36.2.0:

      Successfully uninstalled setuptools-36.2.0

  Rolling back uninstall of setuptools

Exception:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main

    status = self.run(options, args)

  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run

    prefix=options.prefix_path,

  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install

    **kwargs

  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install

    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)

  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files

    isolated=self.isolated,

  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/site-packages/pip/wheel.py", line 247, in move_wheel_files

    prefix=prefix,

  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/site-packages/pip/locations.py", line 140, in distutils_scheme

    d = Distribution(dist_args)

  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/site-packages/setuptools/dist.py", line 365, in __init__

    self._finalize_requires()

  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/site-packages/setuptools/dist.py", line 372, in _finalize_requires

    if not self.install_requires:

AttributeError: 'Distribution' object has no attribute 'install_requires'
```

**Comment by lwm** [comment]
Seems like a fix follows from https://github.com/pypa/setuptools/issues/1086.
